/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * HandsVeinWindow.java
 *
 * Created on Oct 24, 2012, 11:20:31 AM
 */
package handsveindetection;

import handsveindetection.buisness.FileMonitor;
import java.awt.BorderLayout;
import java.awt.Component;
import java.awt.event.ComponentListener;
import java.awt.event.ContainerEvent;
import java.awt.event.ContainerListener;
import java.io.FileInputStream;
import java.util.Properties;
import javax.swing.JInternalFrame;
import javax.swing.event.InternalFrameAdapter;
import javax.swing.event.InternalFrameEvent;
import javax.swing.event.InternalFrameListener;

/**
 *
 * @author Amar
 */
public class HandsVeinWindow extends javax.swing.JFrame {
    
    /** Creates new form HandsVeinWindow */
    public HandsVeinWindow() {
        initComponents();
       final Properties properties = new Properties();
        try{
              properties.load(new FileInputStream("C:\\Users\\Amar\\Documents\\NetBeansProjects\\HandsVeinDetection\\src\\handsveindetection\\file\\handsvein.properties"));
              deskTopPane.addContainerListener(new ContainerListener() {

                    @Override
                    public void componentAdded(ContainerEvent e) {
                  //     FileMonitor.startFileMonitor(properties.getProperty("directory"), properties.getProperty("fileextension"));
                        Component component = e.getComponent();
                       //  System.out.println("Class "+component.getClass().getName());
                         if(component instanceof JInternalFrame){
                         System.out.println("component AddedLOgin");
                             registrationButton.setEnabled(false);
                        }
                        if(component instanceof JInternalFrame ){
                             loginButton.setEnabled(false);
                     
                        }
                        System.out.println("component Added");
                    }

                    @Override
                    public void componentRemoved(ContainerEvent e) {
                        Component component = e.getComponent();
                         if(component instanceof HansVeinLogin){
                            registrationButton.setEnabled(true);
                         }
                        if(component instanceof HandsVeinRegistration ){
                            loginButton.setEnabled(true);
                        }
                        registrationButton.setEnabled(true);
                        loginButton.setEnabled(true);
                    //     FileMonitor.stopFileMonitor();
                      System.out.println("componentremoved");
                    }
         });
         }catch(Exception t){
            t.printStackTrace();
        }
        
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        loginButton = new javax.swing.JButton();
        registrationButton = new javax.swing.JButton();
        deskTopPane = new javax.swing.JDesktopPane();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jPanel1.setPreferredSize(new java.awt.Dimension(619, 23));

        loginButton.setText("Login");
        loginButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginButtonActionPerformed(evt);
            }
        });

        registrationButton.setText("Registration");
        registrationButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registrationButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(loginButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 452, Short.MAX_VALUE)
                .addComponent(registrationButton))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(loginButton)
                    .addComponent(registrationButton))
                .addContainerGap(4, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 600, Short.MAX_VALUE)
            .addComponent(deskTopPane, javax.swing.GroupLayout.DEFAULT_SIZE, 600, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(deskTopPane, javax.swing.GroupLayout.DEFAULT_SIZE, 492, Short.MAX_VALUE))
        );

        setBounds(0, 0, 616, 568);
    }// </editor-fold>//GEN-END:initComponents

private void loginButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginButtonActionPerformed

 logframe.add( hansVeinLogin, BorderLayout.CENTER ); 
 logframe.pack();
 logframe.setLocation(0,0);
 logframe.setVisible(true);
 deskTopPane.removeAll();
 deskTopPane.add(logframe); 
 
}//GEN-LAST:event_loginButtonActionPerformed

private void registrationButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registrationButtonActionPerformed

 regframe.add( handsVeinRegistration, BorderLayout.CENTER ); 
 regframe.pack();
 regframe.setLocation(0,0);
 regframe.setVisible(true);
 deskTopPane.removeAll();
 deskTopPane.add(regframe);                           
}//GEN-LAST:event_registrationButtonActionPerformed


    JInternalFrame logframe = new JInternalFrame("HandsVeinLogin Form", true, true, true, true );
    JInternalFrame regframe = new JInternalFrame( "HandsveinRegistration Form", true, true, true, true );
    HandsVeinRegistration handsVeinRegistration = new HandsVeinRegistration();
    HansVeinLogin hansVeinLogin   = new HansVeinLogin();
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane deskTopPane;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton loginButton;
    private javax.swing.JButton registrationButton;
    // End of variables declaration//GEN-END:variables
}
